name: Clepsy
options:
  bundleIdPrefix: com.clepsy
  deploymentTarget:
    iOS: "16.0"
  developmentLanguage: en

settings:
  SWIFT_VERSION: "5.9"
  MARKETING_VERSION: "1.0.0"
  CURRENT_PROJECT_VERSION: "1"

targets:
  Clepsy:
    type: application
    platform: iOS
    sources:
      - Clepsy
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.clepsy.app
        INFOPLIST_FILE: Clepsy/Info.plist
        CODE_SIGN_ENTITLEMENTS: Clepsy/Clepsy.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    info:
      path: Clepsy/Info.plist
      properties:
        CFBundleDisplayName: Clepsy
        CFBundleShortVersionString: "1.0.0"
        CFBundleVersion: "1"
        UILaunchScreen: {}
        NSFamilyControlsUsageDescription: "Clepsy needs permission to monitor app usage and manage screen time to help you trade productive time for social media access."
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
    dependencies:
      - framework: FamilyControls.framework
        type: framework
      - framework: ManagedSettings.framework
        type: framework
      - framework: DeviceActivity.framework
        type: framework
    scheme:
      testTargets:
        - ClepsyTests
    entitlements:
      path: Clepsy/Clepsy.entitlements
      properties:
        com.apple.developer.family-controls: true

  ClepsyTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - ClepsyTests
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.clepsy.app.tests
    dependencies:
      - target: Clepsy
